# Generated by Django 5.2 on 2025-04-23 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_tasklist"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="list",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="api.tasklist",
            ),
        ),
    ]
