# Generated by Django 5.2 on 2025-04-24 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_task_list"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tasklist",
            old_name="listname",
            new_name="listName",
        ),
    ]
