# Generated by Django 5.2 on 2025-04-24 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_rename_listname_tasklist_listname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasklist",
            name="listOwner",
        ),
    ]
